# Generated by Django 5.1.6 on 2025-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_stripe_session_id_payments_stripe_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="stripe_session_id",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="stripe_status",
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "наличные"), ("transfer", "перевод на счет")],
                default="cash",
                max_length=10,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
