# Generated by Django 5.1.7 on 2025-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_lessons_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите цену курса",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
